// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8g43NDLu0dh0LC538KXbhWs4mgW_Uc0M',
    appId: '1:296230532879:web:b35715c0d2fbc499c4f07a',
    messagingSenderId: '296230532879',
    projectId: 'boat-service-hygwell',
    authDomain: 'boat-service-hygwell.firebaseapp.com',
    storageBucket: 'boat-service-hygwell.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUS_VpYoJZaxgjNs3zwWYbFi8zDA9bPU',
    appId: '1:296230532879:android:25ffc331606b62d8c4f07a',
    messagingSenderId: '296230532879',
    projectId: 'boat-service-hygwell',
    storageBucket: 'boat-service-hygwell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0gmmuQEHq1zFWzHUHioETS2YK3wdW-A',
    appId: '1:296230532879:ios:9738d674b7f7782ac4f07a',
    messagingSenderId: '296230532879',
    projectId: 'boat-service-hygwell',
    storageBucket: 'boat-service-hygwell.appspot.com',
    iosBundleId: 'com.example.boatServiceHygwell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe0gmmuQEHq1zFWzHUHioETS2YK3wdW-A',
    appId: '1:296230532879:ios:9738d674b7f7782ac4f07a',
    messagingSenderId: '296230532879',
    projectId: 'boat-service-hygwell',
    storageBucket: 'boat-service-hygwell.appspot.com',
    iosBundleId: 'com.example.boatServiceHygwell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8g43NDLu0dh0LC538KXbhWs4mgW_Uc0M',
    appId: '1:296230532879:web:f45f05d0aca93defc4f07a',
    messagingSenderId: '296230532879',
    projectId: 'boat-service-hygwell',
    authDomain: 'boat-service-hygwell.firebaseapp.com',
    storageBucket: 'boat-service-hygwell.appspot.com',
  );
}
